apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tomato-secret-vault
  namespace: tomato
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore

  target:
    name: tomato-secret-vault

  data:
  - secretKey: GOOGLE_CLIENT_ID
    remoteRef:
      key: tomato
      property: GOOGLE_CLIENT_ID

  - secretKey: GOOGLE_CLIENT_SECRET
    remoteRef:
      key: tomato
      property: GOOGLE_CLIENT_SECRET

  - secretKey: JWT_SEC
    remoteRef:
      key: tomato
      property: JWT_SEC

  - secretKey: MONGO_URI
    remoteRef:
      key: tomato
      property: MONGO_URI
