
apiVersion: v1
kind: ConfigMap
metadata:
  name: tomato-config
  namespace: tomato
data:
  MONGO_URI: "mongodb://mongodb:27017/Zomato_Clone"

  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"

  RESTAURANT_SERVICE: "http://restaurant:5001"
  AUTH_SERVICE: "http://auth:5000"
  RIDER_SERVICE: "http://rider:5005"
  UTILS_SERVICE: "http://utils:5002"
  REALTIME_SERVICE: "http://realtime:5004"

  PAYMENT_QUEUE: "payment_event"

  INTERNAL_SERVICE_KEY: "jdfienf12345@@@@##4$$$%%%jsadfjlajdf"

  JWT_SEC: "my-super-secret-key-123"
---
apiVersion: v1
kind: Secret
metadata:
  name: tomato-secret
  namespace: tomato
type: Opaque
stringData:
  GOOGLE_CLIENT_ID: "P301605069487-dgr3h7m4cudj4iu9avm7u0ufp6tt0k3u.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "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"

  CLOUD_NAME: "mgqs8jw0"
  CLOUD_API_KEY: "941916313949319"
  CLOUD_SECRET_KEY: "9GaQQBAoBbZ0iaQLtDCILErlPVE"

  STRIPE_SECRET_KEY: "sk_test_51U4xIOLZcNhZj6sXv7B6cZbROYOT6WrW3Vu8Nwdh5BIUugC3tyYUydl3eYXdg9R9K412cMsNJXO5k54FYs4vcmqv00tBUEexLd"

  RAZORPAY_KEY_ID: "rzp_test_TQL5UwAdnOjozR"
  RAZORPAY_KEY_SECRET: "s9DSL5uoVGulXIdMf7TrqtJL"
